name: antauri
description: "The most advance desktop entry manager."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.1.3'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  bitsdojo_window: ^0.1.6
  get: ^4.6.6
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  sealed_languages: ^1.5.0
  path: ^1.8.3
  flutter_svg: ^2.0.10+1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tabs/
    - assets/icons/controls/
    - assets/animations/

  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-Medium.ttf
          weight: 500
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700